Add PlatformStatus.External field
openshift/api pull request #738
Opened 2020-09-16 14:11 UTC by Danil-Grigorev

2020-09-17 12:44 UTC, Danil-Grigorev commented
/retest

2020-09-18 14:00 UTC, michaelgugino requested changes
We don't need this change.

We should deduce in the KCM operator which options to use based on the platform we're using.  We're not making this configurable for users.

2020-09-21 13:40 UTC, Danil-Grigorev commented
> We don't need this change.
> 
> We should deduce in the KCM operator which options to use based on the platform we're using. We're not making this configurable for users.

Would an annotation on this resource be a sufficient/ok temporal change not exposed in the API to trigger the transition? This would be a simple change

2021-02-03 13:27 UTC, Danil-Grigorev commented
/remove-lifecycle rotten

2021-02-03 13:41 UTC, Danil-Grigorev commented
/test verify

2021-06-29 20:33 UTC, elmiko reviewed
i was reading through this code again, and had a question

2021-06-29 20:33 UTC, elmiko commented on config/v1/types_feature.go
> +		"ExternalCloudProvider",
should we have a comment here?
```suggestion
		"ExternalCloudProvider", // sig-cloud-provider, danil-grigorev, elmiko
```

2021-07-30 02:09 UTC, closed without merging