Update operatorhub config object to v1
openshift/api pull request #896
Opened 2021-04-14 15:45 UTC by kevinrizza

Update the operatorhub config API to CRD v1

2021-04-14 15:45 UTC, kevinrizza commented
/bugzilla refresh

2021-04-14 15:46 UTC, dinhxuanvu approved these changes
/lgtm

2021-04-14 15:52 UTC, dinhxuanvu approved these changes
/lgtm

2021-04-15 12:51 UTC, kevinrizza commented
/test verify

2021-04-15 15:52 UTC, soltysh requested changes

2021-04-15 15:52 UTC, soltysh commented on config/v1/0000_03_config-operator_01_operatorhub.crd.yaml
>    subresources:
This is misplaced, should be under versions.

2021-04-20 14:20 UTC, kevinrizza commented
@soltysh Updated and verify is passing now. Ptal :)

2021-04-20 14:44 UTC, soltysh approved these changes
/lgtm
/approve

2021-04-20 14:46 UTC, merged