Add machine.openshift.io API definitions
openshift/api pull request #948
Opened 2021-06-22 12:46 UTC by alexander-demichev

Add machine.openshift.io API definitions. This PR adds Machine and AWSProviderConfig definitions.
https://issues.redhat.com/browse/OCPCLOUD-693

2021-06-23 09:55 UTC, alexander-demichev commented on machine/v1beta1/common_types.go
> +package v1beta1
yes, it's all plain copy-paste from MAO repo

2021-06-23 10:49 UTC, alexander-demichev commented on machine/v1beta1/types_awsproviderstatus.go
> +type AWSMachineProviderStatus struct {
Yes, I copied it from AWS provider. We don't need TypeMeta there but I don't think it should be removed since this is already shipped API

2021-06-23 11:04 UTC, soltysh requested changes
A couple of questions:
- Any particular reason for having this many files instead of a single `types.go`? 
- Where are the yaml files for these types, they should be living next to go types?

2021-06-24 12:44 UTC, alexander-demichev commented
> Any particular reason for having this many files instead of a single types.go?

I reduced the number of files, now there are only files for Machine object and for AWS Provider Spec/Status.

> Where are the yaml files for these types, they should be living next to go types?

`update-codegen-crds` doesn't generate them, I can't find what I missed.

2021-06-28 07:33 UTC, soltysh commented
> I reduced the number of files, now there are only files for Machine object and for AWS Provider Spec/Status.

I'd suggest squashing `common_types.go` and `conditions.go` into `type_provider.go`

> `update-codegen-crds` doesn't generate them, I can't find what I missed.

They are not automatically generated unfortunately. We only update the manually written ones with the additions from types, but you need to write them initially by hand.

2021-06-30 16:02 UTC, alexander-demichev commented
@soltysh Can I get another round of review?

2021-07-09 12:02 UTC, alexander-demichev commented
/retest

2021-07-13 16:15 UTC, soltysh approved these changes
A few nits and you need verify green.
/approve

2021-07-13 16:15 UTC, soltysh commented on machine/v1beta1/0000_10_machine.crd.yaml
> +  creationTimestamp: null
nit: not needed.

2021-07-13 16:15 UTC, soltysh commented on machine/v1beta1/0000_10_machine.crd.yaml
> +status:
nit: drop the status bits

2021-08-03 12:27 UTC, alexander-demichev commented
/retest

2021-08-19 10:17 UTC, soltysh approved these changes
/lgtm

2021-09-03 11:55 UTC, alexander-demichev commented
/retest

2021-09-06 07:52 UTC, merged